name: build_$(Date:yyyyMMdd)$(Rev:r)
 
trigger:
  - main



stages:
  
  - stage: build
    jobs: 
      - job: build_on_linux
        pool:
          name: "Default"
        steps:
          - template: templates/anisiblePipline/CI_template.yaml

  - stage: DeployStaging
    dependsOn: build
    condition: succeeded()      
    jobs:
      - job:
        pool:
          name: "Default"
        steps:
          - template: templates/anisiblePipline/CD_Staging_template.yaml

  - stage: DeployProduction
    dependsOn: DeployStaging
    condition: succeeded()
    jobs:
    - deployment: continues_delivery
      displayName: continues_delivery
      environment: Production
      pool:
        name: "production"
      strategy:
        runOnce:
          deploy:          
            steps:
              - template: templates/anisiblePipline/CD_Production_template.yaml
