

trigger:
- master
- feature/*

# pool:
#   name: Azure Pipelines

# variables:
#   YOURVARKEYS: YOURVARVALUES
  

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    pool:
      name: stagingPool
    workspace: 
      clean: all
    steps:
    #- template: templates/DockerPipeline/CI_template.yaml
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConnection'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: 'bootcamp'
        command: 'buildAndPush'
        Dockerfile: '$(Build.Repository.LocalPath)'


# Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     environment:
#       name: staging
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: templates/DockerPipeline/CD_template.yaml
          



# Continuous Delivery Process for Production Environment
# - stage: DeployToProduction
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: production
#     displayName: Deploy to Production
#     environment:
#       name: production
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
          