---
- hosts: "{{ group }}"
  become: true
  vars_files:  
    - "{{ Var_file }}/"

  tasks:

  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600

  - name: Transfer folder from agentServer to hosting servers
    synchronize:
      src: /home/adminuser/myagent/_work/1/s/
      dest: /home/adminuser/bootcamp-app
  - name: Transfer file from agentServer to hosting servers
    synchronize:
      src: /home/adminuser/myagent/_work/1/s/.env
      dest: /home/adminuser/bootcamp-app

  # - name: env
  #   copy:
  #     dest: "/home/adminuser/bootcamp-app/.env"
  #     content: |
  #         # Host configuration
  #         PORT={{ http_port }}
  #         HOST=0.0.0.0
  #         HOST_URL=http://{{ public_ip }}:{{ http_port }}
  #         COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
  #         NODE_ENV=development
  #         # Okta configuration
  #         OKTA_ORG_URL=https://{{ okta_org_url }}
  #         OKTA_CLIENT_ID={{ okta_client_id }}
  #         OKTA_CLIENT_SECRET={{ okta_client_secret }}
  #         # Postgres
  #         PGHOST={{ pg_host }} 
  #         PGUSERNAME={{ pg_username }}
  #         PGDATABASE={{ pg_database }}
  #         PGPASSWORD={{ pg_password }}
  #         PGPORT=5432
  
  - name: Update nodejs package

    shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

  - name: Install nodejs
    become: true
    shell: apt-get install -y nodejs

#  - name:
#    become: true
#    shell: npm audit fix

  - name: Install node dependencies
    shell: npm install
    become: true
    args:
      chdir: "/home/adminuser/bootcamp-app"

  - name: Database initialization
    shell: npm run initdb
    async: 30
    poll: 0
    args:
      chdir: "/home/adminuser/bootcamp-app"

  - name: Install pm2
    shell: npm install pm2@latest -g

  - name: Run application
    shell: pm2 start npm -- run dev && pm2 save && pm2 startup
    args:
      chdir: "/home/adminuser/bootcamp-app"