---
- hosts: "{{ group }}"
  become: true

  tasks:

  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600
  
    
      
  - name: Transfer folder from agentServer to hosting servers
    synchronize:
      src: /home/adminuser/myagent/_work/1/s/
      dest: /home/adminuser/bootcamp-app

  - name: Transfer file from agentServer to hosting servers
    synchronize:
      src: /home/adminuser/myagent/_work/1/s/.env
      dest: /home/adminuser/
  - name: install unzip
    become: true
    shell: apt install unzip

  - nam: npm $ nodejs
    become: true
    shell: sudo curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs           
  
  - name: install dotenv
    become: true
    shell: npm install dotenv    
  - name: Database initialization
    shell: npm run initdb
    async: 30
    poll: 0
    args:
      chdir: "/home/adminuser/bootcamp-app"

  - name: Install pm2
    shell: npm install pm2@latest -g

  - name: Run application
    shell: pm2 start npm -- run dev && pm2 save && pm2 startup
    args:
      chdir: "/home/adminuser/bootcamp-app"

