---
- hosts: "{{ group }}"
  become: true
  vars_files:
    - "Vars.yaml"
  
- jobs:
    - job:
      steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '{{ deploy_directory }}'
            Contents: '**'
            TargetFolder: '{{ deploy_directory }}'    




  tasks:

   
    - name: Database initialization
      shell: npm run initdb
      async: 30
      poll: 0
      args:
        chdir: "{{ deploy_directory }}/"

    - name: Install pm2
      shell: npm install pm2@latest -g

    - name: Run application
      shell: pm2 start npm -- run dev && pm2 save && pm2 startup
      args:
        chdir: "{{ deploy_directory }}/"


