---
- hosts: "{{ group }}"
  become: true
  vars_files:
    - "Vars.yaml"
  
  
  tasks:

  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600

  - name: copy files from ServerA to ServerB
    copy:
      src: /home/adminuser/myagent/_work/1/s
      dest: /home/adminuser/bootcamp-app

  - name: Install node dependencies
    shell: npm install
    become: true
    args:
      chdir: "/home/adminuser/bootcamp-app/s"

  - name: Npm initialization
    shell: npm init -y
    become: true 
    args:
     chdir: "/home/adminuser/bootcamp-app/s"  
  
  # - name: Database initialization
  #   shell: npm run initdb
  #   async: 30
  #   poll: 0
  #   args:
  #     chdir: "/home/adminuser/bootcamp-app/s"

  # - name: Install pm2
  #   shell: npm install pm2@latest -g

  # - name: Run application
  #   shell: pm2 start npm -- run dev && pm2 save && pm2 startup
  #   args:
  #     chdir: "/home/adminuser/bootcamp-app/s"

