- group: bootcamp-appBuildVar


http_port: $(http_port)
public_ip: $(production_public_ip)

deploy_directory: $(deploy_directory)
pg_host: $(production_host)
pg_username: $(pg_username)
pg_database: $(pg_database)
pg_password: $(pg_password)
okta_org_url: $(okta_org_url)
okta_client_id: $(okta_client_id)
okta_client_secret: $(okta_client_secret)