---
- hosts: "{{ group }}"
  become: true
  vars_files:
    - vars

  tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600  

  - script: |
      cat  << EOF > .env
      # Host configuration
      PORT= {{ http_port }}
      HOST=0.0.0.0
      HOST_URL=http://{{public_ip}}:{{ http_port }}
      COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
      NODE_ENV=development
      # Okta configuration
      OKTA_ORG_URL=https://{{ okta_org_url }}
      OKTA_CLIENT_ID={{ okta_client_id }}
      OKTA_CLIENT_SECRET={{ okta_client_secret }}
      # Postgres
      PGHOST={{ pg_host }}
      PGUSERNAME={{ pg_username }}
      PGDATABASE={{ pg_database }}
      PGPASSWORD={{ pg_password }}
      PGPORT=5432
      EOF
